### ISSUE TITLE
Unable to download corpora other than English

### ISSUE THREAD

**Issue by wangxuxuxuw** [facebookresearch/muavic#11]
Downloading mtedx_el.tgz from https://www.openslr.org/resources/100/mtedx_el.tgz
Traceback (most recent call last):
  File "/home/w30043779/miniconda3/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/w30043779/miniconda3/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/w30043779/miniconda3/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/w30043779/miniconda3/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/w30043779/miniconda3/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/w30043779/miniconda3/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/w30043779/miniconda3/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/w30043779/miniconda3/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/w30043779/miniconda3/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/home/w30043779/miniconda3/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/w30043779/code1/muavic-main/utils.py", line 62, in download_file
    wget.download(url, out=str(download_path / filename), bar=custom_bar)
  File "/home/w30043779/miniconda3/lib/python3.10/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/home/w30043779/miniconda3/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/w30043779/miniconda3/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/w30043779/miniconda3/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/w30043779/miniconda3/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/w30043779/miniconda3/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/w30043779/miniconda3/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/w30043779/miniconda3/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/w30043779/code1/muavic-main/get_data.py", line 115, in <module>
    main(args)
  File "/home/w30043779/code1/muavic-main/get_data.py", line 84, in main
    prepare_mtedx(args)
  File "/home/w30043779/code1/muavic-main/get_data.py", line 15, in prepare_mtedx
    download_mtedx_data(args["mtedx"], args["src_lang"], args["src_lang"])
  File "/home/w30043779/code1/muavic-main/mtedx_utils.py", line 27, in download_mtedx_data
    download_extract_file_if_not(
  File "/home/w30043779/code1/muavic-main/utils.py", line 89, in download_extract_file_if_not
    download_file(url, download_path)
  File "/home/w30043779/code1/muavic-main/utils.py", line 65, in download_file
    raise HTTPError(e.url, e.code, message, e.hdrs, e.fp)
AttributeError: 'URLError' object has no attribute 'url'

**Comment by Anwarvic** [comment]
Hi @wangxuxuxuw ,

Sorry for the inconvenience and thanks a lot for posting the error trace in your post.

On my end, I couldn't reproduce your error. And to be honest, I don't think it's related to our code in the first place. However, I'm more than happy to help you fix it. But first, try out the solutions in these posts ([here](https://www.howtouselinux.com/post/ssl-certificate_verify_failed-in-python), [here](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/42334357#42334357), and [here](https://stackoverflow.com/a/51408997/5612363)) and get back to me if nothing works.

Hope this helps!
