### ISSUE TITLE
Could you please tell me what version your 'sox' is?

### ISSUE THREAD

**Issue by Yangxiaoda1** [facebookresearch/muavic#19]
It tells me that sox can't handle flac files and encounters "sox.core.SoxiError: SoXI failed with exit code 1" in several places.

**Comment by Anwarvic** [comment]
Hi @Yangxiaoda1 ,

Thanks for raising this issue!

To be fair, this is not a bug in our code, I think your `sox` setup is corrupted or the downloaded file is corrupted. So, here is how I installed `sox` for this project:
```
conda install -c conda-forge sox
```

Also, the current version of `sox` that I have on my computer is `sox:  SoX v14.4.2`. If the issue didn't get resolved, then please post the whole error trace.

**Comment by Yangxiaoda1** [comment]
My version of SoX is also v14.4.2. I redownloaded SoX, but it hasn't been resolved yet. The trace is:

Traceback (most recent call last):
  File "get_data.py", line 115, in <module>
    main(args)
  File "get_data.py", line 84, in main
    prepare_mtedx(args)
  File "get_data.py", line 23, in prepare_mtedx
    preprocess_mtedx_audio(args["mtedx"], args["src_lang"], args["muavic"])
  File "/root/autodl-tmp/muavic/mtedx_utils.py", line 126, in preprocess_mtedx_audio
    process_map(
  File "/root/miniconda3/envs/general/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 105, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/root/miniconda3/envs/general/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/root/miniconda3/envs/general/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/general/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/root/miniconda3/envs/general/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/root/miniconda3/envs/general/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/root/miniconda3/envs/general/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
sox.core.SoxiError: SoXI failed with exit code 1

It also used to report an error saying that sox couldn't handle flac files, and I ended up converting the .flac file to a wav file before it worked.

**Comment by Anwarvic** [comment]
Hi @Yangxiaoda1, thanks for the update!

Since the problem has been solved, could you close this issue? Thx
