### ISSUE TITLE
Error when preprocessing the video data

### ISSUE THREAD

**Issue by joyolee** [facebookresearch/muavic#2]
Dear authors,

  thanks a lot for this contribution to multi-lingual AV-ASR! I have an error when preprocessing the video data. This error happens in: https://github.com/facebookresearch/muavic/blob/122ef0cae876db1a9f0ec8a0382f5f090ddf8b7f/mtedx_utils.py#L190-L201
  The error is as follows, did you also happen to have this error or do you have some clues to solve it? :

```
  0%|          | 0/95 [00:00<?, ?it/s]
  0%|          | 0/95 [00:05<?, ?it/s]
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/process.py", line 368, in _queue_management_worker
    result_item = result_reader.recv()
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 2 required positional arguments: 'stdout' and 'stderr'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "get_data.py", line 77, in <module>
    main(args)
  File "get_data.py", line 59, in main
    prepare_mtedx(args)
  File "get_data.py", line 22, in prepare_mtedx
    preprocess_mtedx_video(
  File "/beegfs/work/zhengyangli/muavic/mtedx_utils.py", line 190, in preprocess_mtedx_video
    process_map(
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 105, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

**Comment by Anwarvic** [comment]
Hey @joyolee , 

The `BrokenProcessPool` error basically means that one or more of the processes has terminated unexpectedly. Mostly, this happens due to out of memory error.

Thanks to your comment, our team has re-factored this part and I think it should work just fine now. All you need to do is update the source code using:
```
git pull
```

Also, you don't need to clean or deleted any of the already downloaded/created files. Our code takes care of that as well. Please, feel free to close once the issue is resolved!
