### ISSUE TITLE
RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for AVHubertSeq2Seq:

### ISSUE THREAD

**Issue by RichardLin1999** [facebookresearch/muavic#21]
Traceback (most recent call last):
  File "/home/lpl/muavic/demo/run_demo.py", line 220, in <module>
    AV_RESOURCES = load_av_models(args.av_models_path)
  File "/home/lpl/muavic/demo/demo_utils.py", line 65, in load_av_models
    models, _, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/lpl/av_hubert/fairseq/fairseq/checkpoint_utils.py", line 447, in load_model_ensemble_and_task
    model.load_state_dict(
  File "/home/lpl/av_hubert/fairseq/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AVHubertSeq2Seq:
        size mismatch for decoder.layers.0.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.0.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.1.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.1.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.2.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.2.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.3.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.3.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.4.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.4.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.5.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for decoder.layers.5.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        
        I'm having this issue, pls is there any solution？

**Comment by Anwarvic** [comment]
Hi @RichardLin1999,

Sorry that you are facing this issue! This issue is about a missmatch between the decoder's expected dimension (which is `1024` in this case) and the decoder's size of the loaded checkpoint (which is `765` in this case).

So, sre you trying to load a finetuned checkpoint from the [provided checkpoints](https://github.com/facebookresearch/muavic/tree/main?tab=readme-ov-file#models) in our repo, or this is your fine-tuned checkpoint? If it's selected from our repo, please point out to which one you used. If it's your checkpoint, please upload it to any storage service (e.g. GoogleDrive) so we can replicate your error.

**Comment by RichardLin1999** [comment]
sorry the problem before is resolved, but I have another problem when  I try to use demo website , when I try to upload a video made by myself . It has the error below.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/lpl/muavic/demo/run_demo.py", line 173, in process_input_video
    AV_RESOURCES[model_type]["model"],
KeyError: 'model'

It seems like the model is null value. But I download the checkpoint from your github.

**Comment by Pol-Buitrago** [comment]
> Hi @RichardLin1999,
> 
> Sorry that you are facing this issue! This issue is about a missmatch between the decoder's expected dimension (which is `1024` in this case) and the decoder's size of the loaded checkpoint (which is `765` in this case).
> 
> So, sre you trying to load a finetuned checkpoint from the [provided checkpoints](https://github.com/facebookresearch/muavic/tree/main?tab=readme-ov-file#models) in our repo, or this is your fine-tuned checkpoint? If it's selected from our repo, please point out to which one you used. If it's your checkpoint, please upload it to any storage service (e.g. GoogleDrive) so we can replicate your error.

Hi @Anwarvic,

I'm also experiencing the same error when trying to load different checkpoints. I've noticed that I can only get it to work with the English checkpoint provided in the repository. However, when attempting to use any other checkpoint, I receive the same size mismatch error related to the decoder.

I would appreciate any guidance on how to resolve this issue. Thanks in advance for your help!

```
Traceback (most recent call last):
  File "infer_AVSR.py", line 130, in <module>
    hypo = predict(task_type, video_path=mouth_roi_path, audio_path=audio_path, user_dir=user_dir)
  File "infer_AVSR.py", line 83, in predict
    models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
  File "/gpfs/projects/bsc88/speech/research/repos/av_hubert/fairseq/fairseq/checkpoint_utils.py", line 450, in load_model_ensemble_and_task
    model.load_state_dict(
  File "/gpfs/projects/bsc88/speech/research/repos/av_hubert/fairseq/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/bsc/bsc915220/.conda/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AVHubertSeq2Seq:
	size mismatch for decoder.layers.0.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.0.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.1.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.1.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.2.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.2.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.3.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.3.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.4.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.4.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.5.encoder_attn.k_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for decoder.layers.5.encoder_attn.v_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
```
