### ISSUE TITLE
Got error when preparing LRS3

### ISSUE THREAD

**Issue by MrSupW** [facebookresearch/muavic#5]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "get_data.py", line 107, in <module>
    main(args)
  File "get_data.py", line 73, in main
    prepare_lrs3(args)
  File "get_data.py", line 53, in prepare_lrs3
    process_lrs3_videos(args["lrs3"], args["metadata"], args["muavic"])
  File "/mnt/pfs/wanghe/corpus/muavic/muavic/lrs3_utils.py", line 239, in process_lrs3_videos
    process_map(
  File "/opt/conda/envs/oslasr/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 130, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/opt/conda/envs/oslasr/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/opt/conda/envs/oslasr/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/oslasr/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/opt/conda/envs/oslasr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/opt/conda/envs/oslasr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/conda/envs/oslasr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
AssertionError: /mnt/pfs/wanghe/corpus/muavic/metadata/en/train/FPhZGDS6kVQ.pkl should've been downloaded!

**Comment by Anwarvic** [comment]
Hi @MrSupW,

Thanks for submitting this issue.

Two quick questions:

1. have you downloaded the [LRS3 dataset](https://mmai.io/datasets/lip_reading/) successfully?
2. If yes, have you extracted it and placed it inside `${ROOT}/lrs3` directory?

**Comment by MrSupW** [comment]
Thanks for your quick reply! @Anwarvic 
Yes, I have successfully downloaded LRS3, extraceted it and placed it inside ${ROOT}/lrs3 as shown in the figure below.
By the way, my root path is '/mnt/pfs/wanghe/corpus/muavic'
![image](https://user-images.githubusercontent.com/57617568/225959863-f1ba41fc-d4c7-4384-90ec-a0fb82852e10.png)

**Comment by Anwarvic** [comment]
Hi again @MrSupW,

The error indicates that the metadata file (`/mnt/pfs/wanghe/corpus/muavic/metadata/en/train/FPhZGDS6kVQ.pkl`) is missing!

Could you double check if all English metadata (located at `/mnt/pfs/wanghe/corpus/muavic/metadata/en_metadata.tgz`) has been downloaded and extracted successfully or not?

**Comment by MrSupW** [comment]
@Anwarvic I rechecked and it was true that en_metadata.tgz was not decompressed correctly. I manually unzipped it and then re-ran get_data.py without problems.

**Comment by Anwarvic** [comment]
Glad that it worked eventually! I'm gonna close this issue now.
