### ISSUE TITLE
download_ted2020() error

### ISSUE THREAD

**Issue by MrSupW** [facebookresearch/muavic#6]
It seems that you try to parse a zip file using GzipFile?
Here is the traceback:
Downloading el-en.txt.zip from https://opus.nlpl.eu/download.php?f=TED2020/v1/moses/el-en.txt.zip
 MBTraceback (most recent call last):
  File "get_data.py", line 107, in <module>
    main(args)
  File "get_data.py", line 73, in main
    prepare_lrs3(args)
  File "get_data.py", line 59, in prepare_lrs3
    download_ted2020(args["ted2020"])
  File "/mnt/pfs/wanghe/corpus/muavic/muavic/lrs3_utils.py", line 345, in download_ted2020
    extract_ted2020_data(str(tgz_filepath), "en", lang, ted2020_path)
  File "/mnt/pfs/wanghe/corpus/muavic/muavic/lrs3_utils.py", line 308, in extract_ted2020_data
    tmx_dict = xmltodict.parse(GzipFile(tgz_filepath))
  File "/opt/conda/envs/oslasr/lib/python3.8/site-packages/xmltodict.py", line 372, in parse
    parser.ParseFile(xml_input)
  File "/opt/conda/envs/oslasr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/opt/conda/envs/oslasr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/conda/envs/oslasr/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/opt/conda/envs/oslasr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'PK')

**Comment by Anwarvic** [comment]
Hi @MrSupW ,

Thanks for submitting this issue. It was a simple change in the TED2020 dataset URL. Please, run `git pull` to update the current repo with the latest changes.

Thanks!

**Comment by MrSupW** [comment]
download_ted2020 function is all good now
But a new problem arises in prepare_lrs3_avst_manifests function. Here is the traceback@Anwarvic 
Extracting en-el: 100%|██████████| 262659/262659 [00:00<00:00, 814098.07it/s]
Extracting en-es: 100%|██████████| 405955/405955 [00:00<00:00, 1101689.57it/s]
Extracting en-fr: 100%|██████████| 399853/399853 [00:00<00:00, 958119.07it/s] 
Extracting en-it: 100%|██████████| 363786/363786 [00:00<00:00, 944902.82it/s]
Extracting en-pt: 100%|██████████| 320286/320286 [00:00<00:00, 883210.78it/s] 
Extracting en-ru: 100%|██████████| 380270/380270 [00:00<00:00, 675357.42it/s]

Creating AVST manifests
en-el AVST manifest:   0%|          | 0/3 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "get_data.py", line 107, in <module>
    main(args)
  File "get_data.py", line 73, in main
    prepare_lrs3(args)
  File "get_data.py", line 60, in prepare_lrs3
    prepare_lrs3_avst_manifests(args["mt_trans"], args["ted2020"], args["muavic"])
  File "/mnt/pfs/wanghe/corpus/muavic/muavic/lrs3_utils.py", line 401, in prepare_lrs3_avst_manifests
    split_ids = read_txt_file(
  File "/mnt/pfs/wanghe/corpus/muavic/muavic/utils.py", line 27, in read_txt_file
    with open(txt_filepath) as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/pfs/wanghe/corpus/muavic/mt_trans/en-x/train_id.txt'

**Comment by Anwarvic** [comment]
Hi @MrSupW ,

Thanks for highlighting this issue! The code responsible for downloading `'/mnt/pfs/wanghe/corpus/muavic/mt_trans/en-x.tgz` (which has `train_id.txt` file that causing your issue) was missing. I've updated the public repo with the missing code. Please, run `git pull` to update your repo with the latest code version. 

Thanks again for raising these issues!

**Comment by MrSupW** [comment]
Ok, It;s all good now!
